### ISSUE TITLE
run ha addon as amd64?

### ISSUE THREAD

**Issue by sphen13** [plord12/webscrapers#1]
if i wanted to run the addon as amd64 - would i just swap the entry in the Dockerfile? also unsure in the dockerfile where the file 'ha_ss-linux-arm64' its referencing is from. thanks!

**Comment by plord12** [comment]
I've just pushed a amd64 version of the Dockerfile, although I can't test it.  So I suspect you could :

```
make bin/ha_ss-linux-amd64
cd ha_ss_addon
ssh root@homeassistant mkdir -p /addons/ha_ss_addon
scp Dockerfile* *.yaml run.sh root@homeassistant:/addons/ha_ss_addon
scp ../bin/ha_ss-linux-amd64 root@homeassistant:/addons/ha_ss_addon
```

Also updated the readme a little.

and, yes, I know this isn't great.  But its what I have right now.

**Comment by sphen13** [comment]
thx - tried real quick and get some errors (i did have to change the files you committed a bit to ensure it was all amd64 fyi).  i did not build direct on HAOS as i dont know how to do that - but i did on a ubuntu machine. maybe thats the source of my issues. i get this error:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/ha_ss-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /ha_ss-linux-amd64)
/ha_ss-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /ha_ss-linux-amd64)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```

i may look into how to compile for haos specifically - but need to travel home first! :)

thanks!

**Comment by plord12** [comment]
I've re-built mine (arm64) and it still works okay.

I did spot this post - https://kupczynski.info/posts/glibc-not-found/, I'm wondering if you have built with a different go version (I have 1.23.3).

**Comment by plord12** [comment]
If it helps, I've shared a local build here https://github.com/plord12/webscrapers/releases/tag/v0.0.0-alpha

**Comment by sphen13** [comment]
well i must have done something dumb when compiling myself. this is working great. just wrestling with css selectors but it is working great! thanks.

**Comment by plord12** [comment]
Great !  I did add a little more docs on CSS selector.

I'll close this issue.
